# Troubleshooting: https://github.com/marketplace/actions/actions-template-sync#troubleshooting

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # submodules: true
          token: ${{ secrets.SYNC_FROM_UPSTREAM }}

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2 # Docs: https://github.com/marketplace/actions/actions-template-sync
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: olivercaine/ultimate-app
          upstream_branch: main
          is_pr_cleanup: true # Update when upstream branch is changed
          is_keep_branch_on_pr_cleanup: true # Create new PR but keep existing branch
